name: My First workflow
on: [push]
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: List and Read Files
        run: |
            echo "Hello, welcome to my first GitHub Actions workflow!"
            ls -ltra
            cat README.md
